### ISSUE TITLE
Using mistiConfig.json inside project

### ISSUE THREAD

**Issue by emochka2007** [nowarp/blueprint-misti#2]
### Description
Attempting to add functionality to the Blueprint project with the `mistiConfig.json` results in an error when initializing with the provided data. The expected array for "detectors" was not found, indicating a possible issue with the configuration structure.

### Current Behavior
Running the command:
`npx blueprint misti --config mistiConfig.json contracts/tactConfig.json`
Results in the following error:
```bash
⏳ Checking the project...
Error: An error occurred: Error: Failed to initialize Config with provided data: [
{
"code": "invalid_type",
"expected": "array",
"received": "undefined",
"path": [
"detectors"
],
"message": "Required"
}
]
```
### Misti Configuration (mistiConfig.json)
```json
{
  "detectorsEnabled": [
    { "className": "DivideBeforeMultiply" },
    { "className": "ReadOnlyVariables" },
    { "className": "NeverAccessedVariables" },
    { "className": "UnboundLoops" },
    { "className": "ZeroAddress" },
    { "className": "BranchDuplicate" },
    { "className": "FieldDoubleInit" },
    { "className": "PreferAugmentedAssign" }
  ],
  "ignoredProjects": [],
  "unusedPrefix": "_",
  "verbosity": "default"
}

**Comment by jubnzv** [comment]
Thanks for reporting this! An incorrect option name was used in the configuration. To bypass this, please change `detectorsEnabled` to `detectors` in the configuration file.
